on:
  workflow_call:
    inputs:
      cmake_args:
        required: true
        type: string

      cmake_build:
        required: true
        type: string

steps:
- name: CMake config
  run: cmake -B ${{github.workspace}}/build ${{cmake_args}} -DCMAKE_BUILD_TYPE=${{parameters.cmake_build}} -DSCENEPIC_BUILD_TESTS=1 -DSCENEPIC_BUILD_DOCUMENTATION=1

- name: CMake build
  run: cmake --build ${{github.workspace}}/build --config ${{cmake_build}} --target cpp

- name: CMake test
  working-directory: ${{github.workspace}}/build
  run: ctest -V --build-config ${{cmake_build}} --timeout 120 --output-on-failure -T Test

  workingDirectory: './build'
  displayName: CTest
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/Test.xml'
  inputs:
    testResultsFormat: CTest
    testResultsFiles: '**/Test.xml'
    failTaskOnFailedTests: true
