on:
  workflow_call:

steps:
  - name: build wheel
    run: |
      pip install --use-deprecated=legacy-resolver -e .[dev]
      python setup.py bdist_wheel
      python setup.py develop

  - name: Run pytest
    uses: pavelzw/pytest-action@v1
    with:
      verbose: true
      job-summary: true
    run: |
      python -m pytest test

    displayName: PyTest
    continueOnError: true
