parameters:
  - name: vmImage
    default: ""

jobs:
MacPython:
  strategy:
    matrix:
      python.version: ["3.7", "3.8", "3.9", "3.10"]

  runs-on: ${{vmImage}}

  steps:
    - name: Use Python ${{python.version}}
      uses: actions/setup-python@4.2.0
      with:
        python-version: ${{python.version}}

    - name: Get dependencies
      run: |
        python -m pip install --upgrade pip
        brew install doxygen

    - name: "NPM steps"
      uses: ./.github/workflows/reuseable/npm-steps.yml

    - name: Build and Test Python
      uses: ./.github/workflows/reuseable/build-and-test-python.yml

MacCPP:
  runs-on: ${{vmImage}}

  steps:
    - name: Use Python 3.8
      uses: actions/setup-python@4.2.0
      with:
        python-version: "3.8"

    - name: Get dependencies
      run: |
        python -m pip install --upgrade pip
        brew install doxygen

    - name: NPM steps
      uses: ./.github/workflows/reuseable/npm-steps.yml

    - name: Build and Test C++
      uses: ./.github/workflows/reuseable/build-and-test-cpp.yml
      with:
        cmake_args: -G"Unix Makefiles"
        cmake_build: ${{cmake.build}}
