name: Windows Job

on:
  workflow_call:
    inputs:
      vmImage:
        required: true
        type: string

jobs:
  WindowsPython:
    strategy:
      matrix:
        python.version: ["3.7", "3.8", "3.9"]
        python.arch: [x86, x64]
        include:
          - python.version: "3.10"
            python.arch: x64

    runs-on: ${{vmImage}}

    steps:
      - name: Use Python ${{python.version}}
        uses: actions/setup-python@4.2.0
        with:
          python-version: ${{python.version}}
          architecture: ${{python.arch}}

      - name: Get dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
              
          cd ci
          python download_deps.py

      - name: "NPM steps"
        uses: ./.github/workflows/reuseable/npm-steps.yml

      - name: Build and Test Python
        uses: ./.github/workflows/reuseable/build-and-test-python.yml

  WindowsCPP:
    runs-on: ${{vmImage}}

    strategy:
      matrix:
        cmake.build: [Release, Debug]

    steps:
      - name: Use Python 3.8
        uses: actions/setup-python@4.2.0
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Get dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

          cd ci
          python download_deps.py

      - name: NPM steps
        uses: ./.github/workflows/reuseable/npm-steps.yml

      - name: Build and Test C++
        uses: ./.github/workflows/reuseable/build-and-test-cpp.yml
        with:
          cmake_args: -G"Visual Studio 17 2022" -Ax64
          cmake_build: ${{cmake.build}}

      - name: CMake install
        run: cmake --build ${{github.workspace}}/build --config ${{cmake.build}} --target INSTALL
