pr:
- main

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  displayName: Use Python 3.7
  inputs:
    versionSpec: 3.7

- script: |
    pip install -r requirements-flake8.txt
  displayName: Install flake8

- script: |
    flake8 src/scenepic test --format "##vso[task.logissue type=error;sourcepath=%(path)s;linenumber=%(row)s;columnnumber=%(col)s;code=%(code)s;]%(text)s"
  displayName: Run flake8
